name: Publish
on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@v0.1
        with:
          ref: master # can be commit SHA or tag too
          check-name: test_runner # name of the existing check
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20 # seconds

      - name: Upload
        uses: onichandame/pip-upload-action@master
        with:
          username: '__token__'
          password: ${{ secrets.PIP_PASSWORD }}