name: Publish
on:
  push:
    branches:
      - develop
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      # - name: Test
      #   uses: onichandame/python-test-action@master
        
      - name: Upload
        uses: onichandame/pip-upload-action@master
        with:
          username: '__token__'
          password: ${{ secrets.PIP_PASSWORD }}